PROGRAM BENCH_CUDA
        USE FIELD_MODULE
        USE FIELD_FACTORY_MODULE
        USE PARKIND1
        IMPLICIT NONE

        CLASS(FIELD_4IM), POINTER :: F1,F2
        INTEGER(KIND=JPIM), ALLOCATABLE :: D(:,:,:,:)
        INTEGER(KIND=JPIM) :: NPROMA, NFLEVG, NGPBLKS, DELTA_TRUC
        INTEGER(KIND=JPIM), POINTER :: PTR(:,:,:,:)

        NPROMA=64
        NFLEVG=100
        DELTA_TRUC=100
        NGPBLKS=100

        ALLOCATE(D(NPROMA,NFLEVG,DELTA_TRUC,NGPBLKS))
        D=7

        CALL FIELD_NEW(F1, DATA=D(:,:,50:,4:80), PERSISTENT=.TRUE.)
        CALL F1%GET_DEVICE_DATA_RDWR(PTR)
        !$ACC KERNELS DEFAULT(PRESENT)
        PTR=PTR*2
        !$ACC END KERNELS
        CALL F1%SYNC_HOST_RDONLY()
        CALL FIELD_DELETE(F1)
END
