PROGRAM CPU_TO_GPU_PINGPONG
        !TEST CPU TO GPU TRANSFER SPEEDS
        !TEST INITIALISING DATA ON CPU THEN MOVING THEM ON GPU

        USE FIELD_MODULE
        USE FIELD_FACTORY_MODULE
        USE PARKIND1
        IMPLICIT NONE
        CLASS(FIELD_3RB), POINTER :: O => NULL()
        REAL(KIND=JPRB), POINTER :: PTR_HOST(:,:,:) => NULL()
        REAL(KIND=JPRB), POINTER :: PTR_DEV(:,:,:) => NULL()
        INTEGER ::I,J,IT
        LOGICAL :: OKAY

        CALL FIELD_NEW(O, LBOUNDS=[1,1,1], UBOUNDS=[32,137,1024], PERSISTENT=.TRUE.)

        DO IT=1,1000
        CALL O%GET_DEVICE_DATA_RDWR(PTR_DEV)
        CALL O%GET_HOST_DATA_RDWR(PTR_HOST)
        ENDDO

        CALL FIELD_DELETE(O)
END PROGRAM CPU_TO_GPU_PINGPONG
